# Add polynomial features example

In [1]:
import polynomial
import numpy as np
import pandas as pd

### Generate dummy DataFrame

In [2]:
size = 10

coefficients = [6.2,-1.4,2.3]
x = np.ones((size,len(coefficients)))
for i in range(1,len(coefficients)):
    x[:,i]=np.random.rand(size)
x = pd.DataFrame(x,columns=['A','B','C'])

** Adding new features **

In [3]:
polynomial.add_polynimials(x,2,3)

,A,B,C,A^2,B^2,C^2,A^2_x_B,A_x_B^2,A^2_x_C,A_x_C^2,B^2_x_C,B_x_C^2
0,1.0,0.235766,0.716437,1.0,0.055585,0.513282,0.235766,0.055585,0.716437,0.513282,0.039823,0.121014
1,1.0,0.478485,0.737459,1.0,0.228948,0.543846,0.478485,0.228948,0.737459,0.543846,0.168840,0.260223
2,1.0,0.225219,0.154158,1.0,0.050724,0.023765,0.225219,0.050724,0.154158,0.023765,0.007819,0.005352
3,1.0,0.501207,0.932855,1.0,0.251208,0.870219,0.501207,0.251208,0.932855,0.870219,0.234341,0.436160
4,1.0,0.227786,0.587296,1.0,0.051886,0.344916,0.227786,0.051886,0.587296,0.344916,0.030473,0.078567
5,1.0,0.018405,0.844656,1.0,0.000339,0.713444,0.018405,0.000339,0.844656,0.713444,0.000286,0.013131
6,1.0,0.598213,0.468264,1.0,0.357859,0.219271,0.598213,0.357859,0.468264,0.219271,0.167573,0.131171
7,1.0,0.039848,0.251853,1.0,0.001588,0.063430,0.039848,0.001588,0.251853,0.063430,0.000400,0.002528
8,1.0,0.999062,0.613221,1.0,0.998126,0.376040,0.999062,0.998126,0.613221,0.376040,0.612072,0.375687
9,1.0,0.535284,0.960923,1.0,0.286529,0.923373,0.535284,0.286529,0.960923,0.923373,0.275332,0.494266

** Excluding series by name **

In [6]:
polynomial.add_polynimials(x,2,3,skip_row=['B'])

     A         B         C  A^2       C^2   A^2_x_C   A_x_C^2
0  1.0  0.235766  0.716437  1.0  0.513282  0.716437  0.513282
1  1.0  0.478485  0.737459  1.0  0.543846  0.737459  0.543846
2  1.0  0.225219  0.154158  1.0  0.023765  0.154158  0.023765
3  1.0  0.501207  0.932855  1.0  0.870219  0.932855  0.870219
4  1.0  0.227786  0.587296  1.0  0.344916  0.587296  0.344916
5  1.0  0.018405  0.844656  1.0  0.713444  0.844656  0.713444
6  1.0  0.598213  0.468264  1.0  0.219271  0.468264  0.219271
7  1.0  0.039848  0.251853  1.0  0.063430  0.251853  0.063430
8  1.0  0.999062  0.613221  1.0  0.376040  0.613221  0.376040
9  1.0  0.535284  0.960923  1.0  0.923373  0.960923  0.923373

** Excluding series by index **

In [7]:
polynomial.add_polynimials(x,2,3,skip_row=[0,2])

     A         B         C       B^2
0  1.0  0.235766  0.716437  0.055585
1  1.0  0.478485  0.737459  0.228948
2  1.0  0.225219  0.154158  0.050724
3  1.0  0.501207  0.932855  0.251208
4  1.0  0.227786  0.587296  0.051886
5  1.0  0.018405  0.844656  0.000339
6  1.0  0.598213  0.468264  0.357859
7  1.0  0.039848  0.251853  0.001588
8  1.0  0.999062  0.613221  0.998126
9  1.0  0.535284  0.960923  0.286529

** Also works directly on numpy arrays ** <br>
not recommended, because tracking the order of added columns could be tricky

In [18]:
x.values.shape

(10, 3)

In [17]:
add_polynimials(x.values,4,7).shape

(10, 30)