# Add polynomial features example

In [1]:
import polynomial
import numpy as np
import pandas as pd

### Generate dummy DataFrame

In [2]:
size = 10

coefficients = [6.2,-1.4,2.3]
x = np.ones((size,len(coefficients)))
for i in range(1,len(coefficients)):
    x[:,i]=np.random.rand(size)
x = pd.DataFrame(x,columns=['A','B','C'])

In [3]:
x

     A         B         C
0  1.0  0.486511  0.784041
1  1.0  0.695155  0.899680
2  1.0  0.240757  0.370826
3  1.0  0.490845  0.055799
4  1.0  0.898880  0.362686
5  1.0  0.628043  0.683074
6  1.0  0.257819  0.310643
7  1.0  0.149865  0.451799
8  1.0  0.914821  0.500797
9  1.0  0.761334  0.899581

** Adding new features **

In [4]:
polynomial.add_polynimials(x,2,3)

,A,B,C,A^2,B^2,C^2,A^2_x_B,A_x_B^2,A^2_x_C,A_x_C^2,B^2_x_C,B_x_C^2
0,1.0,0.486511,0.784041,1.0,0.236693,0.614720,0.486511,0.236693,0.784041,0.614720,0.185577,0.299068
1,1.0,0.695155,0.899680,1.0,0.483241,0.809423,0.695155,0.483241,0.899680,0.809423,0.434762,0.562675
2,1.0,0.240757,0.370826,1.0,0.057964,0.137512,0.240757,0.057964,0.370826,0.137512,0.021495,0.033107
3,1.0,0.490845,0.055799,1.0,0.240928,0.003113,0.490845,0.240928,0.055799,0.003113,0.013443,0.001528
4,1.0,0.898880,0.362686,1.0,0.807986,0.131541,0.898880,0.807986,0.362686,0.131541,0.293045,0.118240
5,1.0,0.628043,0.683074,1.0,0.394438,0.466590,0.628043,0.394438,0.683074,0.466590,0.269430,0.293038
6,1.0,0.257819,0.310643,1.0,0.066470,0.096499,0.257819,0.066470,0.310643,0.096499,0.020649,0.024879
7,1.0,0.149865,0.451799,1.0,0.022460,0.204122,0.149865,0.022460,0.451799,0.204122,0.010147,0.030591
8,1.0,0.914821,0.500797,1.0,0.836897,0.250798,0.914821,0.836897,0.500797,0.250798,0.419116,0.229435
9,1.0,0.761334,0.899581,1.0,0.579629,0.809245,0.761334,0.579629,0.899581,0.809245,0.521423,0.616106

** Excluding series by name **

In [5]:
polynomial.add_polynimials(x,2,3,skip_row=['B'])

     A         B         C  A^2       C^2   A^2_x_C   A_x_C^2
0  1.0  0.486511  0.784041  1.0  0.614720  0.784041  0.614720
1  1.0  0.695155  0.899680  1.0  0.809423  0.899680  0.809423
2  1.0  0.240757  0.370826  1.0  0.137512  0.370826  0.137512
3  1.0  0.490845  0.055799  1.0  0.003113  0.055799  0.003113
4  1.0  0.898880  0.362686  1.0  0.131541  0.362686  0.131541
5  1.0  0.628043  0.683074  1.0  0.466590  0.683074  0.466590
6  1.0  0.257819  0.310643  1.0  0.096499  0.310643  0.096499
7  1.0  0.149865  0.451799  1.0  0.204122  0.451799  0.204122
8  1.0  0.914821  0.500797  1.0  0.250798  0.500797  0.250798
9  1.0  0.761334  0.899581  1.0  0.809245  0.899581  0.809245

** Excluding series by index **

In [6]:
polynomial.add_polynimials(x,2,3,skip_row=[0,2])

     A         B         C       B^2
0  1.0  0.486511  0.784041  0.236693
1  1.0  0.695155  0.899680  0.483241
2  1.0  0.240757  0.370826  0.057964
3  1.0  0.490845  0.055799  0.240928
4  1.0  0.898880  0.362686  0.807986
5  1.0  0.628043  0.683074  0.394438
6  1.0  0.257819  0.310643  0.066470
7  1.0  0.149865  0.451799  0.022460
8  1.0  0.914821  0.500797  0.836897
9  1.0  0.761334  0.899581  0.579629

** Also works directly on numpy arrays ** <br>
not recommended, because tracking the order of added columns could be tricky

In [7]:
x.values.shape

(10, 3)

In [8]:
polynomial.add_polynimials(x.values,4,7).shape

(10, 30)